In [ ]:
#본인의 이름과 학번을 출력하는 코드를 작성하시오.
print("김솔아")
print("202116266")

In [4]:
# myemail 변수를 만들고 자신의 이메일을 저장하시오. myphone 변수를 만들고 010-xxxx-xxxx 휴대폰 번호를 저장하시오.
myemail = "codkan20@gmail.com"
myphone = "010-2977-5662"
print(myemail)
print(myphone)

codkn20@gmail.com
010-2977-5662


In [231]:
# testdata.csv 파일에 저장된 데이터 중 <제목>에 빅데이터 용어가 몇 번 출현했는지 찾아내는 코드를 작성하시오. Big Data, Big-Data, BIg data, big-data, BIG DATA 등등을 모두 카운트할 수 있어야 한다.
import pandas as pd
import glob
import re
from functools import reduce
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from collections import Counter
import matplotlib.pyplot as plt
from wordcloud import STOPWORDS, WordCloud
pd.__version__

s = "bigdata Bigdata Bigdatadalsdf big-data biggigigbigdata Big-DAta"
p = re.compile("bigdata", re.I)
q = re.compile("big-data", re.I)

string = p.findall(s)
string1 = q.findall(s)
print(string1)
print(string)
print(len(string))
# import nltk
# nltk.download('stopwords')
#
# stopWords = set(stopwords.words('english'))
# lemma = WordNetLemmatizer()
#
# for title in all_title:
#     EnWords = re.sub(r"[^a-zA-Z]+", " ", str(title))
#     EnWordsToken = word_tokenize(EnWords.lower())
#     EnWordsTokenStop = [w for w in EnWordsToken if w not in
#                                    stopWords]
#     EnWordsTokenStopLemma = [lemma.lemmatize(w) for w in
#                                             EnWordsTokenStop]
#     words.append(EnWordsTokenStopLemma
#
# count = Counter(words2) #딕셔너리객체 생성 => 단어의 빈도수를 count해줌
# count
string


['big-data', 'Big-DAta']
['bigdata', 'Bigdata', 'Bigdata', 'bigdata']
4


['bigdata', 'Bigdata', 'Bigdata', 'bigdata']

In [14]:
# myemail에서 ID만을 추출하여 myid 변수로 저장하고 출력하는 코드를 작성하시오
myemail = "codkan20@gmail.com"
myid = myemail[0:8]
print(myid)



'codkan20'

In [17]:
# myphone에서 마지막 숫자4개만 추출하여 mynumber 변수로 저장하고 출력하는 코드를 작성하시오.
myphone = "010-2977-5662"
mynumber = myphone[9:13]
mynumber


'5662'

In [57]:
# myclass 데이터 테이블을 pandas의 DataFrame 자료형으로 저장하고 출력하시오. 컬럼은 Mid, Final, Report 이고, index는 본인의 학번, 본인의학번+1, +2, +3, +4 이다. 점수는 자유롭게 정하여 기록한다. 100점 만점으로. 예) 98 88 90
c1 = pd.Series([99,99,89,88,85])
c2 = pd.Series([90,99,90,88,85])
c3 = pd.Series([90,99,91,88,85])
i = [202116266, 202116267, 202116268, 202116269, 202116270]
myclass = pd.concat([c1,c2,c3], axis =1)
df = myclass.set_index(keys=[i], inplace=False, drop=False)
df.columns = ["Mid","Final", "Report"]
print(df)



           Mid  Final  Report
202116266   90     90      90
202116267   99     99      99
202116268   89     90      91
202116269   88     88      88
202116270   85     85      85


In [86]:
# 5명 학생의 Mid 평균을 구하고 출력하시오.
c1 = pd.Series([99,99,89,88,85])
c2 = pd.Series([90,99,90,88,85])
c3 = pd.Series([90,99,91,88,85])
i = [202116266, 202116267, 202116268, 202116269, 202116270]
myclass = pd.concat([c1,c2,c3], axis =1)
df = myclass.set_index(keys=[i], inplace=False, drop=False)
df.columns = ["Mid","Final", "Report"]
print(df)

a= str(df.mean(axis=0)[0])
print("Mid평균 => ", a)



           Mid  Final  Report
202116266   90     90      90
202116267   99     99      99
202116268   89     90      91
202116269   88     88      88
202116270   85     85      85
Mid평균 =>  90.2


In [126]:
# 본인의 Mid, Final, Report 평균을 구하고 출력하시오.
c1 = pd.Series([99,99,89,88,85])
c2 = pd.Series([90,99,90,88,85])
c3 = pd.Series([90,99,91,88,85])
i = [202116266, 202116267, 202116268, 202116269, 202116270]
myclass = pd.concat([c1,c2,c3], axis =1)
df = myclass.set_index(keys=[i], inplace=False, drop=False)
df.columns = ["Mid","Final", "Report"]

# df.mean(axis='columns')
a = df.iloc[0].mean()
print(a)

93.0


In [127]:
# 각 학생의 총점을 계산하여 Total 컬럼에 저장하고 myclass를 출력한다. 단, Total 컬럼은 추가해야한다. 또한 총점은 Mid 40%, Final 40% Report 20% 비중으로 더한다.
total = (df["Mid"]*0.4)+(df["Final"]*0.4)+(df["Report"]*0.2)

df["total"]=total

print(df)

           Mid  Final  Report  total
202116266   99     90      90   93.6
202116267   99     99      99   99.0
202116268   89     90      91   89.8
202116269   88     88      88   88.0
202116270   85     85      85   85.0


In [131]:
# 각 학생의 등급을 'Grade'로 저장하고 myclass를 출력한다. Grade는 90점 이상 'A', 80점 이상'B', 70점 이상'C', 60점 이상 'D', 60점 미만 'F'로 정한다.

# if df["total"] >= 90:
#     grade = "A"
# elif df["total"] >= 80:
#     grade = "B"
# elif df["total"] >= 70:
#     grade = "C"
# else :
#     grade = "F"

df["grade"] = pd.cut(total,bins=[0,70,80,90,100],labels=["D","C","B","A"],right=False)
print(df)


           Mid  Final  Report  total grade
202116266   99     90      90   93.6     A
202116267   99     99      99   99.0     A
202116268   89     90      91   89.8     B
202116269   88     88      88   88.0     B
202116270   85     85      85   85.0     B


In [132]:
# 앞에서 추가한 'Grade' 컬럼을 myclass 데이터프레임에서 삭제한다. myclass 데이터프레임을 출력한다.

df = df.drop(['grade'], axis=1)
print(df)


           Mid  Final  Report  total
202116266   99     90      90   93.6
202116267   99     99      99   99.0
202116268   89     90      91   89.8
202116269   88     88      88   88.0
202116270   85     85      85   85.0


In [152]:
# myclass 데이터프레임과 동일한 값을 갖는 넘파이 배열을 생성하고 출력한다. newclass 이름으로 정한다.
import numpy as np
newclass = df.to_numpy()
# newclass = np.array(df.index.values)
newclass


array([[99. , 90. , 90. , 93.6],
       [99. , 99. , 99. , 99. ],
       [89. , 90. , 91. , 89.8],
       [88. , 88. , 88. , 88. ],
       [85. , 85. , 85. , 85. ]])

In [153]:
# newclass 에서 총점 값을 삭제하고 newclass를 출력하여 결과를 확인한다. 다음 코드를 이용한다. np.delete(newclass, 3, axis=1)
print(newclass)
newclass = np.delete(newclass,3, axis=1)
print(newclass)

[[99.  90.  90.  93.6]
 [99.  99.  99.  99. ]
 [89.  90.  91.  89.8]
 [88.  88.  88.  88. ]
 [85.  85.  85.  85. ]]


array([[99., 90., 90.],
       [99., 99., 99.],
       [89., 90., 91.],
       [88., 88., 88.],
       [85., 85., 85.]])

In [173]:
# 새로운 5x3 넘파이 배열(이름은 hahaha)을 생성하고 출력하시오. 값은 랜덤함수를 이용하여 40<= ~ <=100 범위에서 정수값으로 입력한다.

hahaha = np.random.randint(40,101,size=(5,3))
hahaha

array([[ 67,  64,  47],
       [100,  85,  59],
       [ 40,  58,  49],
       [ 78,  68,  49],
       [ 88,  63,  93]])

In [189]:
# hahaha와 newclass 를 하나의 배열( hanew )로 통합하고 hanew를 출력하시오. hahaha 데이터값이 0~4에 위치하고, newclass가 5~9에 위치한다. hanew는 10x3 배열이어야 한다.
hanew = np.concatenate((hahaha, newclass),axis=0)
hanew

array([[ 67.,  64.,  47.],
       [100.,  85.,  59.],
       [ 40.,  58.,  49.],
       [ 78.,  68.,  49.],
       [ 88.,  63.,  93.],
       [ 99.,  90.,  90.],
       [ 99.,  99.,  99.],
       [ 89.,  90.,  91.],
       [ 88.,  88.,  88.],
       [ 85.,  85.,  85.]])

In [192]:
# 브로드캐스팅 을 이용하여 hanew에 저장된 값을 환산한 값으로 수정/저장한 후 출력하시오. 0번 열(컬럼) 중간고사 점수는 40%, 1번 열(컬럼) 기말고사 점수는 40%, 2번 열(컬럼) 레포트 점수는 20% 비율로 환산하여 계산된 값으로 수정/저장한다.

hanew[:,0] = hanew[:,0] *0.4
hanew[:,1] = hanew[:,1] *0.4
hanew[:,2] = hanew[:,2] *0.2
hanew

array([[ 4.288, 10.24 ,  1.88 ],
       [ 6.4  , 13.6  ,  2.36 ],
       [ 2.56 ,  9.28 ,  1.96 ],
       [ 4.992, 10.88 ,  1.96 ],
       [ 5.632, 10.08 ,  3.72 ],
       [ 6.336, 14.4  ,  3.6  ],
       [ 6.336, 15.84 ,  3.96 ],
       [ 5.696, 14.4  ,  3.64 ],
       [ 5.632, 14.08 ,  3.52 ],
       [ 5.44 , 13.6  ,  3.4  ]])

In [205]:
# hanew 배열을 이용하여 질문에 답을 찾는 코드를 작성하시오. (출력문 형식은 상관없이, 답을 구하는 코드만 작성하면 충분합니다.) 10명의 학생 중 가장 높은 총점은 몇 점인가?

hanew.sum(axis=1).max()


26.136000000000003

In [206]:
# hanew 배열을 이용하여 질문에 답을 찾는 코드를 작성하시오. (출력문 형식은 상관없이, 답을 구하는 코드만 작성하면 충분합니다.) 10명의 총점 평균은 몇 점인가?
hanew.sum(axis=1).mean()

20.971200000000003

In [214]:
# hanew 배열을 이용하여 질문에 답을 찾는 코드를 작성하시오. (출력문 형식은 상관없이, 답을 구하는 코드만 작성하면 충분합니다.) 총점이 평균보다 높은 학생은 몇 명인가?
a= hanew.sum(axis=1) > hanew.sum(axis=1).mean()
a.sum()

6

In [224]:
c1 = pd.Series([99,99,89,88,85])
c2 = pd.Series([90,99,90,88,85])
c3 = pd.Series([90,99,91,88,85])
i = [202116266, 202116267, 202116268, 202116269, 202116270]
myclass = pd.concat([c1,c2,c3], axis =1)
df = myclass.set_index(keys=[i], inplace=False, drop=False)
df.columns = ["Mid","Final", "Report"]
print(df)
import matplotlib.pyplot as plt

plt.bar(df.iloc["202116266"], df[0], df[1], df[2])
plt.show()

           Mid  Final  Report
202116266   99     90      90
202116267   99     99      99
202116268   89     90      91
202116269   88     88      88
202116270   85     85      85


TypeError: Cannot index by location index with a non-integer key