넘파이 기초

In [30]:
import random

# 파이썬 2차원 리스트 생성(랜덤값 받아와서 입력하기)
SIZE = 5
#0부터 255까지 랜덤값을 리스트 형태로 받아오기
pythonList = [ [random.randint(0,255) for _ in range(SIZE)] for _ in range(SIZE)]

# 리스트를 출력하기
for i in range(SIZE) : #행에 값 넣어주기
    for k in range(SIZE) :  #열에 값 넣어주기
        print("%3d" % pythonList[i][k], end=' ')
    print()
# print()



114 240 226 204  27 
 61 184 172 133  40 
255 229 128 140 134 
 18 131  84 209  59 
222 201   4 199 136 


In [31]:
# 위에서 만든 2차원 리스트의 모든 값에 100 더하는 코드

# 리스트에 100을 더하기
for i in range(SIZE) :
    for k in range(SIZE) :
        pythonList[i][k] += 100

## 리스트를 출력하기
for i in range(SIZE) :
    for k in range(SIZE) :
        print("%3d" % pythonList[i][k], end=' ')
    print()


214 340 326 304 127 
161 284 272 233 140 
355 329 228 240 234 
118 231 184 309 159 
322 301 104 299 236 


In [36]:
import numpy as np

## 넘파이 2차원 배열 생성
SIZE = 5
numpyAry = np.random.randint(0, 255, size=(SIZE, SIZE))

## 배열을 출력하기
print(numpyAry)
print() #이건 띠어쓰기 용도인가..?

## 배열에 100을 더하기
numpyAry += 100

## 배열을 출력하기
print(numpyAry)


[[ 30 125 177  36  41]
 [ 42 163 177  15 165]
 [209 133 249 230 173]
 [180  26 158  20  72]
 [180  18 118  13  47]]

[[130 225 277 136 141]
 [142 263 277 115 265]
 [309 233 349 330 273]
 [280 126 258 120 172]
 [280 118 218 113 147]]


In [41]:
Size = 3
nummm = np.random.randint(0,255, size = (Size,Size))
print(nummm)
print()

nummm *= 2
print(nummm)

nummm.mean()

[[212 107 140]
 [  4 135 252]
 [157 233  74]]

[[424 214 280]
 [  8 270 504]
 [314 466 148]]


292.0

In [1]:
import numpy as np
import random

pythonList = [random.randint(0,255) for _ in range(5)]
print('* 파이썬 리스트 --> ', pythonList)

numpyAry1 = np.array(pythonList)
print('* array(pythonList) --> ', numpyAry1)

numpyAry2 = np.arange(5)
print('* arange(5) --> ', numpyAry2)
numpyAry3 = np.arange(3, 8)
print('* arange(3, 8) --> ', numpyAry3)
numpyAry3 = np.arange(0, 100, 20)
print('* arange(0, 100, 20) --> ', numpyAry3)

* 파이썬 리스트 -->  [78, 151, 187, 33, 147]
* array(pythonList) -->  [ 78 151 187  33 147]
* arange(5) -->  [0 1 2 3 4]
* arange(3, 8) -->  [3 4 5 6 7]
* arange(0, 100, 20) -->  [ 0 20 40 60 80]


In [4]:
numpyAry4 = np.ones(5)
print('* ones(5) --> \n', numpyAry4)
numpyAry5 = np.ones((3,4))
print('* ones((3,4)) )--> \n', numpyAry5)

numpyAry6 = np.zeros(5)
print('* zeros(5)--> ', numpyAry6)

numpyAry7 = np.empty(6)
print('* empty(6)--> ', numpyAry7)

numpyAry8 = np.full(5, 33)
print('* full(5, 33) --> ', numpyAry8)
numpyAry10 = np.full((3,5), 33)
print('* full((3,5), 33) --> \n', numpyAry10)

numpyAry9 = np.identity(5)
print('* identity(5)--> \n', numpyAry9)

* ones(5) --> 
 [1. 1. 1. 1. 1.]
* ones((3,4)) )--> 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
* zeros(5)-->  [0. 0. 0. 0. 0.]
* empty(6)-->  [0. 0. 0. 0. 0. 0.]
* full(5, 33) -->  [33 33 33 33 33]
* full((3,5), 33) --> 
 [[33 33 33 33 33]
 [33 33 33 33 33]
 [33 33 33 33 33]]
* identity(5)--> 
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [6]:
#이미 지정된 데이터 형식을 astype()함수로 변경할 수 있음
import numpy as np
import random

pList1 = [10, 20, 30, 40]
pList2 = [10, 20, 30, 40.0]

numpyAry1 = np.array(pList1)
print(numpyAry1, numpyAry1.dtype)

numpyAry1 = np.array(pList2)
print(numpyAry1, numpyAry1.dtype)

numpyAry2 = np.array(pList1, dtype=np.float32)
print(numpyAry2, numpyAry2.dtype)

numpyAry3 = np.arange(5)
print(numpyAry3, numpyAry3.dtype)

numpyAry4 = np.ones(5)
print(numpyAry4, numpyAry4.dtype)

numpyAry5 = np.ones(5, dtype=np.uint8)
print(numpyAry5, numpyAry5.dtype)

numpyAry6 = numpyAry5.astype(np.float16)
print(numpyAry6, numpyAry6.dtype)


[10 20 30 40] int32
[10. 20. 30. 40.] float64
[10. 20. 30. 40.] float32
[0 1 2 3 4] int32
[1. 1. 1. 1. 1.] float64
[1 1 1 1 1] uint8
[1. 1. 1. 1. 1.] float16


ndim : 배열의 차원 수 또는 배열의 축 수
shape : 배열 각 차원의 크기를 튜플 형태로
size : 배열 원소의 개수
dtype : 배열 내의 원소의 데이터형
itemsize : 배열 내의 원소의 크기를 바이트 단위로 기술
nbytes : 배열 전체 바이트

In [9]:
arr = np.arange(1,6)
print(arr)

print('ndim : ', arr.ndim)
print('shape:',arr.shape) 
print('dtype:',arr.dtype)
print('size:',arr.size)
print('itemsize:',arr.itemsize)
print('nbytes:',arr.nbytes)


[1 2 3 4 5]
ndim :  1
shape: (5,)
dtype: int32
size: 5
itemsize: 4
nbytes: 20


In [14]:
arr = np.arange(9).reshape((3,3))
print(arr)

print('ndim:',arr.ndim)
print('shape:',arr.shape) 
print('dtype:',arr.dtype)
print('size:',arr.size)
print('itemsize:',arr.itemsize)
print('nbytes:',arr.nbytes)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
ndim: 2
shape: (3, 3)
dtype: int32
size: 9
itemsize: 4
nbytes: 36


In [17]:
#산술연산과 브로드캐스팅
# 원래 배열과 숫자는 연산이 될 수 없지만, 넘파이가 다음과 같이 숫자를 동일한 크기의 배열로 만든 후에 연산을 함


import numpy as np
ary = np.random.randint(0,255, size =(2,3))
print(ary)
ary = ary -100
print(ary) 
ary = ary + ary
print(ary)

[[ 97 226 121]
 [252  66 197]]
[[ -3 126  21]
 [152 -34  97]]
[[ -6 252  42]
 [304 -68 194]]


In [19]:
# 배열의 크키가 다른 경우의 연산
import numpy as np

ary1 = np.array([[1,2],[3,4]])
ary2 = np.array([100,200])

ary1+ ary2
# 앞 배열의 크기 2×2에 맞춰서 뒤쪽 배열도 2×2 크기로 확장된 후 연산을 진행함


array([[101, 202],
       [103, 204]])

In [20]:
# 넘파이에 값 수정하기

ary = np.arange(10)
print(ary)
ary[0] = 100
print(ary)

[0 1 2 3 4 5 6 7 8 9]
[100   1   2   3   4   5   6   7   8   9]


In [30]:
ary = np.arange(10)
print(ary)
ary[0]= 100
print(ary[2:5])
print(ary[-1])
print(ary[-2])
print(ary[:])

[0 1 2 3 4 5 6 7 8 9]
[2 3 4]
9
8
[100   1   2   3   4   5   6   7   8   9]


In [33]:
# 슬라이싱 방식으로 부분집합을 먼저 추출한 후 그 값을 변경하는 코드
ary = np.arange(10)
ary[0]= 100
print(ary)
ary_sub1 = ary[3:7]
print(ary_sub1)
ary_sub1[:]=77
print(ary_sub1)
ary

[100   1   2   3   4   5   6   7   8   9]
[3 4 5 6]
[77 77 77 77]


array([100,   1,   2,  77,  77,  77,  77,   7,   8,   9])

In [37]:
#넘파이 배열의 슬라이싱

import random
SIZE = 5    # 원본 크기
startRow,startCol = 1, 1 # 새로운 리스트의 시작 위치
nSIZE = 3   # 새로운 리스트의 크기

## 파이썬 2차원 리스트 생성
value = 1
myList1 = []
for _ in range(SIZE) :
    tmpList= []
    for _ in range(SIZE) :
        tmpList.append(value)
        value += 1
    myList1.append(tmpList)

## 파이썬 2차원 리스트의 출력
for i in range(SIZE) :
    [ print("%3d" % myList1[i][k], end=' ') for k in range(SIZE) ]
    print()


## 파이썬 2차원 리스트의 슬라이싱
myList2 = []
for i in range(startRow, startRow+nSIZE) :
    tmpList = []
    for k in range(startCol, startCol+nSIZE) :
        tmpList.append(myList1[i][k])
    myList2.append(tmpList)
print("---")
## 파이썬 2차원 리스트의 출력
for i in range(nSIZE) :
    [ print("%3d" % myList2[i][k], end=' ') for k in range(nSIZE) ]
    print()
print()


  1   2   3   4   5 
  6   7   8   9  10 
 11  12  13  14  15 
 16  17  18  19  20 
 21  22  23  24  25 
---
  7   8   9 
 12  13  14 
 17  18  19 



In [43]:
ary = np.arange(1,26,1)
print(ary)
ary = ary.reshape(5,5)
print(ary)
ary = ary.reshape(25) #1차원배열로 변환
print(ary)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25]


In [59]:
#2차원 넘파이 배열의 슬라이싱

#간단히 4x4 크기의 배열을 준비
ary = np.arange(1,17)
ary = ary.reshape(4,4)
print(ary)

#한개의 행 추출
print(ary[1])
print(ary[1, 0 :4])
print(ary[1, :])

#인접한 여러행 추출
print(ary[2:]) #3행,4행 추출
print(ary[2:4])
print(ary[2:4, :])

#한개의 열 추출
print(ary[:,1])
# print(ary[,1]) 이건 안됨용
print(ary[0:4, 1])

#인접한 여러열 추출
print(ary[:, 0:2])

#중간부분 추출
print(ary[1:3, 1:3])

#인접하지 않은 여러행 혹은 여러열 추출
print(ary[[1,3]])
print(ary[:, [1,3]])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[5 6 7 8]
[5 6 7 8]
[5 6 7 8]
[[ 9 10 11 12]
 [13 14 15 16]]
[[ 9 10 11 12]
 [13 14 15 16]]
[[ 9 10 11 12]
 [13 14 15 16]]
[ 2  6 10 14]
[ 2  6 10 14]
[[ 1  2]
 [ 5  6]
 [ 9 10]
 [13 14]]
[[ 6  7]
 [10 11]]
[[ 5  6  7  8]
 [13 14 15 16]]
[[ 2  4]
 [ 6  8]
 [10 12]
 [14 16]]


In [68]:
#2차원 넘파이 배열 연결 및 축 전환
ary1=np.zeros((2,2))
ary2=np.ones((2,2))
ary3 = np.concatenate((ary1, ary2), axis=0) # 행방향으로 추가
ary4= np.concatenate((ary1, ary2), axis=1) # 열방향으로 추가
print(ary3)
print(ary4)

#넘파이 배열의 행과 열을 바꾸려면 transpose(1,0) 또는 T 속성을 사용
print(ary3.transpose(1,0))
print(ary4.T)

[[0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]]
[[0. 0. 1. 1.]
 [0. 0. 1. 1.]]
[[0. 0. 1. 1.]
 [0. 0. 1. 1.]]
[[0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]]


In [67]:
import numpy as np
SIZE = 5    # 원본 크기
startRow,startCol = 1, 1 # 새로운 리스트의 시작 위치
nSIZE = 3   # 새로운 리스트의 크기

## 넘파이 2차원 배열 생성
value = 1
myAry1 = np.arange(value, value+(SIZE*SIZE), 1)
myAry1 = myAry1.reshape(SIZE, SIZE)

## 넘파이 2차원 배열 리스트의 출력
# ~~ Code10-05.py의 17~20행과 동일. 단 myAry1을 출력. ~~

## 넘파이 2차원 배열의 슬라이싱
myAry2 = myAry1[startRow:startRow+nSIZE, startCol: startCol+nSIZE].copy()

## 넘파이 2차원 배열의 출력
# ~~ Code10-05.py의 31~34행과 동일. 단 myAry2를 출력. ~~


In [70]:
#단항 수식 함수
# np.abs()는 모두 양수를 반환하고, sign()의 경우 양수는 0을, 음수는 1을 반환 
# np.sqrt()는 루트값을 반환하는데, 음수의 루트값은 nan(Not a Number)로 표시됨

ary = np.array([[-1, -2], [3,4]])
print(ary)
print(np.abs(ary)) # 절댓값
print(np.sign(ary)) # 부호판별
print(np.sqrt(ary)) #제곱근



[[-1 -2]
 [ 3  4]]
[[1 2]
 [3 4]]
[[-1 -1]
 [ 1  1]]
[[       nan        nan]
 [1.73205081 2.        ]]


C:\Users\codka\AppData\Local\Temp/ipykernel_18392/817764902.py:9: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(ary)) #제곱근


In [72]:
#이항 수식 함수
#더하기(add), 빼기(subtract), 곱하기(multiply) 등이 가능함
#np.maximum(배열1, 배열2)는 두 배열 중 큰 값만 추출해서 새 배열을 반환
#np.greater(배열1, 배열2)는 ‘배열1＞배열2’이 경우엔 True, 그렇지 않으면 False로 구성된 새 배열을 반환

ary = np.array([-1, -2])
ary1 = np.array([3,4])
print(np.add(ary,ary1))
print(ary+ary1)
#59페이지까지 공부함


[2 2]
[2 2]


In [8]:
import numpy as np
# np.where( 조건 ,  참일때,  거짓일때 )
ary = np.random.randint(0,255, size =(3,3))
print(ary)
print(np.where(ary<100, 1, 0))

[[190  11 176]
 [120 100 248]
 [194  45 180]]
[[0 1 0]
 [0 0 0]
 [0 1 0]]


In [12]:
# 통계함수
ary1=np.random.randint(0,255, size =10)
print(ary1)
print(ary1.sum())
print(ary1.mean())
ary2=np.random.randint(0,255, size=(3,3))
print(ary2)
print(ary2.sum())
print(ary2.sum(axis=0))  #세로합 구하기(열합)
print(ary2.sum(axis=1))  #가로합 구하기(행합)


[246  42   2 238 129 140 254  56   2 203]
1312
131.2
[[  2 230 171]
 [238  22 231]
 [104 221  30]]
1249
[344 473 432]
[403 491 355]


In [14]:
ary2=np.random.randint(0,255, size=(3,3))
print(ary2)
#128 이상인 항목의 개수를 세는 코드
(ary2>128).sum()

[[197  46  50]
 [192 178  40]
 [138 223  73]]


5

In [16]:
ary2=np.random.randint(0,255, size=(3,3))
print(ary2)
print(ary2.min())
print(ary2.max())


[[116 107   5]
 [ 58  69  44]
 [ 39 225  23]]
5
225


In [20]:
ary1=np.random.randint(0,255, size=10)
print(ary1)
#np.sort() 함수는 배열을 정렬
print(np.sort(ary1))  #오름차순
print(np.sort(ary1)[::-1]) #내림차순

[ 41  48 120 147  10  63  59 204 227 206]
[ 10  41  48  59  63 120 147 204 206 227]
[227 206 204 147 120  63  59  48  41  10]


In [22]:
#중복된 값을 제거하고 하나씩만 남기려면 np.unique() 함수를 사용
ary1=np.random.randint(0,9, size=10)
print(ary1)
print(np.unique(ary1))

[7 8 3 6 8 2 3 4 8 8]
[2 3 4 6 7 8]


In [25]:
#두 배열 중에서 공통된 항목만 추출하려면 np.intersect1d(배열1, 배열2) 함수를 사용
ary1=np.random.randint(0,9, size=10)
print(ary1)
ary2=np.random.randint(0,9,size=10)
print(ary2)
print(np.intersect1d(ary1, ary2))

[2 0 7 4 8 8 2 6 3 1]
[8 4 8 8 6 4 4 8 1 0]
[0 1 4 6 8]


배열 조희

In [32]:
# 인덱스 요소 참조
arr1=np.arange(9)
print(arr1)
print(arr1[2], arr1[-1])

[0 1 2 3 4 5 6 7 8]
2 8


In [40]:
list2 = [[1,2,3], [4,5,6], [7,8,9]]
arr2 = np.array(list2)
print(arr2)
print(arr2[0,1])
arr3 = np.arange(9).reshape((3,3))
print(arr3)
print(arr3[0])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[0 1 2]


In [50]:
#여러 개의 배열 요소 참조할때 범위 지정 - 슬라이싱
# [from_index : to_index] 여기서 to_index는 포함되지 않는다.
arr = np.random.randint(1,55, 7)
print(arr)
print(arr[0:3])
print(arr[:])
print(arr[2:6])

print(arr[::2]) #두칸씩 띠어서 처음부터 끝까지 출력
print(arr[::3])

[13 54 20 29 46 48 19]
[13 54 20]
[13 54 20 29 46 48 19]
[20 29 46 48]
[13 20 46 19]
[13 29 19]


In [55]:
arr=np.arange(1,25).reshape(4,6)
print(arr)
print(arr[1])
print(arr[1:3, 1:5]) #1,2행/1,4열
print(arr[:3,:3])
print(arr[2,::-1]) # ::-1은 거꾸로..
print(arr2[::-1,::-1])

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
[ 7  8  9 10 11 12]
[[ 8  9 10 11]
 [14 15 16 17]]
[[ 1  2  3]
 [ 7  8  9]
 [13 14 15]]
[18 17 16 15 14 13]
[[9 8 7]
 [6 5 4]
 [3 2 1]]


In [57]:
a=np.arange(1,6)
print(a)
even = a%2 ==0
print(a[even])
print(a[a<3])


[1 2 3 4 5]
[2 4]
[1 2]


In [63]:
#축(axis) "집계연산"
# axis=None  :  전체 행렬로 정의
# axis=0        :  행을 기준으로  (같은 반끼리 계산)
# axis=1        :  열을 기준으로  (같은 학년끼리 계산)
a=np.arange(1,10).reshape(3,3)
print(a)
print(a.sum())
print(np.sum(a))
b=a.sum(axis=0)
c=a.sum(axis=1)
print(b)
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
45
[12 15 18]
[ 6 15 24]


In [66]:
a=np.arange(1,9).reshape(2,4)
print(a)
print(a.T)

[[1 2 3 4]
 [5 6 7 8]]
[[1 5]
 [2 6]
 [3 7]
 [4 8]]
